### ISSUE TITLE
Síntesis_Fernando Miguel López

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-3-sintesis-Ferch0419#2]
[Síntesis_Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Ferch0419/files/9472273/Sintesis_Fernando.Miguel.Lopez.pdf)

**Comment by Brisa-4** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
